services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-982223}
      MYSQL_DATABASE: devovs
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ovs-network
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: ./backend/onlinevotingsystem
    environment:
      DB_URL: jdbc:mysql://mysql:3306/devovs
      DB_USER: root
      DB_PASSWORD: ${DB_PASSWORD:-982223}
      JWT_SECRET: ${JWT_SECRET:-9a2f8c4e6b0d71f3e8b925a45747f894a3d6bc70fa8d5e21a15a6d8c3e9f247b}
      ALLOWED_ORIGINS: "*"
      IMAGE_VERIFY_SERVICE_URL: http://imageverify:5001/verify
      FILE_STORAGE_PATH: /app/user_uploads/profiles/
      PROFILE_IMAGE_STORAGE: ${PROFILE_IMAGE_STORAGE:-cloudinary}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME:-dyma4n2c2}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY:-736826671997363}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET:-vpH5Yqw2kogKEDeBIskye0Gl44w}
      CLOUDINARY_FOLDER: ${CLOUDINARY_FOLDER:-online-voting/profiles}
    volumes:
      - uploads:/app/user_uploads/profiles
    # Internal port 8080, Nginx will proxy to it
    networks:
      - ovs-network

  imageverify:
    build: ./backend/imageverify
    environment:
      PORT: 5001
    networks:
      - ovs-network

  frontend:
    build: ./frontend
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - backend
    networks:
      - ovs-network

volumes:
  mysql_data:
  uploads:

networks:
  ovs-network:
    driver: bridge
