spring.application.name=onlinevotingsystem
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/devovs}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:982223}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8080

# JWT Secret
jwt.secret=${JWT_SECRET:9a2f8c4e6b0d71f3e8b925a45747f894a3d6bc70fa8d5e21a15a6d8c3e9f247b}
jwt.expiration=86400000

# App Config
app.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:5173}
app.image-verify-service.url=${IMAGE_VERIFY_SERVICE_URL:http://localhost:5001/verify}
app.file-storage.path=${FILE_STORAGE_PATH:user_uploads/profiles/}
